### PR TITLE
fix: LDAP - Enable `check-for-changes.sh` support

### LINKED ISSUE #4528: bug report: changedetector service is not started when using `ACCOUNT_PROVISIONER=ldap`. So traefik certificate changes are not detected.
### 📝 Preliminary Checks

- [x] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Manually starting the changedetector service via `supervisorctl start changedetector` fixes this. I'm not sure if this breaks something else. But for now it seems to do what I want it to do.

### 👟 Reproduction Steps

_No response_

### 🐋 DMS Version

v15.0.3

### 💻 Operating System and Architecture

Arch

### ⚙️ Container configuration files

```yml

```

### 📜 Relevant log output

```Text

```

### PR DESCRIPTION
**Pull request by FDHoho007**
# Description

Enables the change detector for account provisioner ldap. This is required to watch for changes in the SSL certificates and reload postfix when needed. Therefore the change detector needs to be aware whether he should also watch the file databases for changes.

Fixes #4528 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] If necessary, I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] **I have added information about changes made in this PR to `CHANGELOG.md`**

### CODE REVIEW

File: target/scripts/check-for-changes.sh [hunk 1]
```diff
@@ -72,8 +70,11 @@ function _handle_changes() {
   fi
 
   _ssl_changes
-  _postfix_dovecot_changes
-  _rspamd_changes
+  # For account provisioner LDAP only SSL changes are relevant.
+  if [[ ${ACCOUNT_PROVISIONER} == 'FILE' ]]; then
+    _postfix_dovecot_changes
+    _rspamd_changes
+  fi
```
Comment (polarathene) [inline target/scripts/check-for-changes.sh]: Looks good, just a minor adjustment:
- I'm pretty sure the related comment that was removed at the top of this file was added before Rspamd landed, I think LDAP users can benefit from that too. It's mostly the account file config with Postfix/Dovecot that shouldn't be processed for LDAP.
- I know that LDAP users have configured [relay host support before via the DMS integration](https://docker-mailserver.github.io/docker-mailserver/v15.1/config/advanced/mail-forwarding/relay-hosts/#technical-details), so change detection support there may also be relevant at some point? I've added a TODO comment as I presently lack the time to assess change detection support properly.

```suggestion
  # TODO: Consider support relay host config change support for other provisioners
  if [[ ${ACCOUNT_PROVISIONER} == 'FILE' ]]; then
    _postfix_dovecot_changes
  fi

  _rspamd_changes
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -10,6 +10,7 @@ All notable changes to this project will be documented in this file. The format
 
 - **Internal:**
   - `ENABLE_QUOTAS=1` - When an alias has multiple addresses, the first local mailbox address found will be used for the Dovecot dummy account workaround ([#4581](https://github.com/docker-mailserver/docker-mailserver/pull/4581))
+  - The Change Detector now also runs with Account Provisioner LDAP to watch for changes in the SSL certificates. ([#4627](https://github.com/docker-mailserver/docker-mailserver/pull/4627))
```
Comment (polarathene) [inline CHANGELOG.md]:
```suggestion
  - Change Detection service - Added support for responding to updated DMS config (_Rspamd and TLS certificates_) to `ACCOUNT_PROVISIONER=LDAP` ([#4627](https://github.com/docker-mailserver/docker-mailserver/pull/4627))
```

**Comment by FDHoho007** [comment]
Thank you for the feedback! I implemented both suggested changes.

**Review by polarathene — APPROVED** [review]

**Comment by polarathene** [comment]
LGTM! Thanks for taking time to make a contribution to DMS ❤️

**Comment by polarathene** [comment]
It seems that an rspamd test has been broken. Unclear if that's the fault of this PR, we don't have extensive test coverage with LDAP so it would be with the file based provisioner 🤔 

> ```
> ok 78 [Rspamd] (DKIM) setting all arguments to a custom value works in 1241ms
>
> not ok 79 setup_file failed
> # (from function `refute_output' in file test/test_helper/bats-assert/src/refute_output.bash, line 189,
> #  from function `setup_file' in test file test/tests/parallel/set1/spam_virus/rspamd_full.bats, line 68)
> #   `refute_output --partial 'inet:localhost:11332: Connection refused'' failed
> # 2025-12-26 00:58:42+00:00 INFO  start-mailserver.sh: mail.example.test is up and running
> # -- output should not contain substring --
> # substring (1 lines):
> #   inet:localhost:11332: Connection refused
> # output (628 lines):
> ```

There is quite a few lines like:

```
postfix/smtpd[1590]: warning: connect to Milter service inet:localhost:11332: Connection refused
```

I've tried re-running the test but it failed again. Until it's confirmed that this is due to something other than this PR I don't think I can go ahead and merge 😓

Unfortunately we don't have an ability to pin the version of rspamd supplied from upstream (_I requested it and offered to implement but they declined_), it's possible that some upstream change pulled in also contributes to this failure, in which case any PR will trigger it.

**Comment by FDHoho007** [comment]
Since I am completely new to this codebase i just poked a bit around.
I reverted my last commit but that did not change anything. Therefore I also assume it is due to an upstream change.
I then found out, that rspamd seems to be running according to supervisorctl but the rspamd logs show, that the rspamd_proxy is only started after that:

```
#1351(main) <3b3991>; main; rspamd_fork_worker: prepare to fork process rspamd_proxy (0); listen on: 127.0.0.1:11332
#1351(main) <3b3991>; main; rspamd_fork_worker: prepare to fork process rspamd_proxy (1); listen on: 127.0.0.1:11332
```

The test rspamd_full waits for the service to be running and then immediately tries to trigger rspamd, which has not yet spawned it's workers.
I don't know how this was handled in the past but I assume, that the workers were ready when rspamd reported as running. Maybe rspamd startup times were also faster in before. Therefore maybe we should also add somthing like _wait_for_rspamd_port_in_container?

**Comment by FDHoho007** [comment]
There still seems to be an issue in rspamd_dkim which randomly fails while restarting rspamd with exit code 7
```
 ✗ [Rspamd] (DKIM) argument 'keytype' is applied correctly [2811]
   (from function `assert_success' in file test/test_helper/bats-assert/src/assert_success.bash, line 42,
    in test file test/tests/parallel/set1/spam_virus/rspamd_dkim.bats, line 116)
     `assert_success' failed
   
   -- command failed --
   status : 7
   output (17 lines):
     2025-12-26 11:14:04+00:00 TRACE rspamd-dkim: Options given to this script: 'keytype ed25519'
     2025-12-26 11:14:04+00:00 DEBUG rspamd-dkim: Keytype set to 'ed25519'
     2025-12-26 11:14:04+00:00 INFO  rspamd-dkim: Creating DKIM keys of type 'ed25519' with selector 'mail' for domain 'example.test'
     2025-12-26 11:14:04+00:00 TRACE rspamd-dkim: Creating Rspamd error log
     2025-12-26 11:14:04+00:00 TRACE rspamd-dkim: Running 'rspamadm dkim_keygen -s mail -d example.test -t ed25519 -k /tmp/docker-mailserver/rspamd/dkim/ed25519-mail-example.test.private.txt' as user '_rspamd'
     2025-12-26 11:14:04+00:00 TRACE rspamd-dkim: Running 'grep --quiet --ignore-case --fixed-strings Permission denied /tmp/tmp.C1bcrlXEnG' as user '_rspamd'
     2025-12-26 11:14:04+00:00 INFO  rspamd-dkim: Successfully created DKIM keys
     2025-12-26 11:14:04+00:00 DEBUG rspamd-dkim: Public key written to '/tmp/docker-mailserver/rspamd/dkim/ed25519-mail-example.test.public.txt'
     2025-12-26 11:14:04+00:00 DEBUG rspamd-dkim: Private key written to '/tmp/docker-mailserver/rspamd/dkim/ed25519-mail-example.test.private.txt'
     2025-12-26 11:14:04+00:00 TRACE rspamd-dkim: Running 'ls /tmp/docker-mailserver/rspamd/dkim' as user '_rspamd'
     2025-12-26 11:14:04+00:00 TRACE rspamd-dkim: Running 'cat /tmp/docker-mailserver/rspamd/dkim/ed25519-mail-example.test.private.txt' as user '_rspamd'
     2025-12-26 11:14:04+00:00 DEBUG rspamd-dkim: Permissions on files and directories seem ok
     2025-12-26 11:14:04+00:00 INFO  rspamd-dkim: Supplying a default configuration (to '/tmp/docker-mailserver/rspamd/override.d/dkim_signing.conf')
     2025-12-26 11:14:04+00:00 DEBUG rspamd-dkim: Restarting Rspamd as initial DKIM configuration was supplied
     rspamd: ERROR (not running)
     rspamd: ERROR (abnormal termination)
     2025-12-26 11:14:04+00:00 ERROR rspamd-dkim: Unexpected error occurred :: script = /usr/local/bin/rspamd-dkim  | function = _setup_default_signing_conf | command = supervisorctl restart rspamd | line = 260 | exit code = 7
   --
```
Randomly meaning that in every test run one or more of the tests fail, but it could be any of them.

**Comment by polarathene** [comment]
> The test rspamd_full waits for the service to be running and then immediately tries to trigger rspamd, which has not yet spawned it's workers.
> I don't know how this was handled in the past but I assume, that the workers were ready when rspamd reported as running. Maybe rspamd startup times were also faster in before.

Could be, or could be a change in the CI environment being slower too. I used to run tests in cheap VPS instances that revealed other issues in the past that didn't show up with our CI on Github.

If that were the case though our current release image (_without a fresh build_) should similarly fail, otherwise it'd need to be some recent change somewhere.

> Therefore maybe we should also add somthing like _wait_for_rspamd_port_in_container?

We have a generic port helper method to wait on, that might be sufficient. Or we could potentially monitor logs (_rspamd logs are a separate log file due to verbosity_).

**EDIT:** Oh I see you already contributed that helper. I'm alright with that 👍 

---

> There still seems to be an issue in rspamd_dkim which randomly fails while restarting rspamd with exit code 7

Yeah I've caught that one before too and have detailed it here: https://github.com/docker-mailserver/docker-mailserver/issues/4579

I just rarely having time spare for DMS lately beyond quick support tickets and reviews.

The project could do with more contributors, we lack the momentum alternative mail solutions have in that regard so I'm not sure how relevant DMS will remain beyond it's main differentiator of a single container for simple deployment and configuration.

**Review by polarathene — APPROVED** [review]
Sweet tests are now passing (_DKIM is still racey as noted_), thanks for also improving the rspamd tests! ❤️

I'm happy to merge the contribution now 🚀
